# Generated by Django 5.2.1 on 2025-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('submission_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'ContactMessage',
                'ordering': ['-submission_datetime'],
            },
        ),
    ]
